apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: henrikkyhl/orderapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: orderapi
  ports:
  - port: 80
    nodePort: 31002